# Extra Practice1 : list, dictionary, if, for, while


   __주제 1) 2차원 리스트 연습 : 서울시 지하철역 유동인구 데이터 분석__ <br>
   __주제 2) 사전(dictionary) 생성__<br>
   __주제 3) 복잡한 사전(dictionary) 값 참조하기 : 서울시 지하철역 유동인구 데이터 <br>
   주제 4) 제어문 : if, while, for__ <br>

In [3]:
%%html
<style>
table {float:left}
</style>

#   < 서울 지하철역 유동인구 데이터를 사용한 리스트 생성>

[1] 다음은 서울 지하철역의 2020년 3월 유동인구 자료(출처:http://data.seoul.go.kr, 서울열린데이터광장)의 일부입니다.<br> 자료의 순서는 "노선", "역명", "승차총승객수", "하차총승객수", "총유동인구수"가 반복됩니다. 위 자료는 리스트(변수명: data)에 저장되어 있습니다.
![image.png](./images/image1.png)

__(1) 1차원 리스트인 data 리스트를 참조하여 2차원 리스트(station_list)를 생성하세요__

In [ ]:
data=['1호선', '동대문', 253079, 250266, 503345, '1호선', '동묘앞', 201255, 210176, 411431, '1호선', '서울역', 815894, 776303, 1592197, '1호선', '시청', 437824, 444220, 882044, '1호선', '신설동', 314759, 307700, 622459, '1호선', '제기동', 362048, 370559, 732607, '1호선', '종각', 744396, 728555, 1472951, '1호선', '종로3가', 555451, 525826, 1081277, '1호선', '종로5가', 468370, 472936, 941306, '1호선', '청량리(서울시립대입구)', 454237, 450838, 905075, '2호선', '강남', 1880213, 1903343, 3783556, '2호선', '강변(동서울터미널)', 706391, 696987, 1403378, '2호선', '건대입구', 814571, 875981, 1690552, '2호선', '교대(법원.검찰청)', 719617, 801630, 1521247, '2호선', '구로디지털단지', 1330385, 1334002, 2664387, '2호선', '구의(광진구청)', 541621, 528622, 1070243, '2호선', '낙성대', 186490, 179479, 365969, '2호선', '낙성대(강감찬)', 425422, 408827, 834249, '2호선', '당산', 431363, 494583, 925946, '2호선', '대림(구로구청)', 540012, 545748, 1085760, '2호선', '도림천', 25872, 27070, 52942, '2호선', '동대문역사문화공원', 79362, 89125, 168487, '2호선', '동대문역사문화공원(DDP)', 174793, 194399, 369192, '2호선', '뚝섬', 450225, 485238, 935463, '2호선', '문래', 438218, 450292, 888510, '2호선', '방배', 347335, 358666, 706001, '2호선', '봉천', 543382, 504075, 1047457, '2호선', '사당', 808536, 881598, 1690134, '2호선', '삼성(무역센터)', 1013824, 1037733, 2051557, '2호선', '상왕십리', 298738, 286419, 585157, '2호선', '서울대입구(관악구청)', 1077608, 1046950, 2124558, '2호선', '서초', 429483, 425905, 855388, '2호선', '선릉', 1184993, 1061005, 2245998, '2호선', '성수', 727213, 796804, 1524017, '2호선', '시청', 491715, 492576, 984291, '2호선', '신답', 35487, 39793, 75280, '2호선', '신당', 308483, 320541, 629024, '2호선', '신대방', 602640, 578785, 1181425, '2호선', '신도림', 1039776, 1017501, 2057277, '2호선', '신림', 1498306, 1448207, 2946513, '2호선', '신설동', 74492, 76794, 151286, '2호선', '신정네거리', 197761, 205895, 403656, '2호선', '신촌', 746651, 773435, 1520086, '2호선', '아현', 202282, 195111, 397393, '2호선', '양천구청', 135312, 141488, 276800, '2호선', '역삼', 1029654, 1137055, 2166709, '2호선', '영등포구청', 491480, 499742, 991222, '2호선', '왕십리(성동구청)', 358762, 303423, 662185, '2호선', '용답', 56847, 56376, 113223, '2호선', '용두(동대문구청)', 50860, 52970, 103830, '2호선', '을지로3가', 436574, 436813, 873387, '2호선', '을지로4가', 269077, 267629, 536706, '2호선', '을지로입구', 800104, 821652, 1621756, '2호선', '이대', 239904, 249460, 489364, '2호선', '잠실(송파구청)', 1478434, 1432775, 2911209, '2호선', '잠실나루', 288199, 279801, 568000, '2호선', '잠실새내', 442061, 448444, 890505, '2호선', '종합운동장', 137270, 147149, 284419, '2호선', '충정로(경기대입구)', 220702, 231292, 451994, '2호선', '한양대', 143613, 154133, 297746, '2호선', '합정', 684322, 729438, 1413760, '2호선', '홍대입구', 1179133, 1251987, 2431120, '3호선', '가락시장', 188435, 183724, 372159, '3호선', '경복궁(정부서울청사)', 358800, 358877, 717677, '3호선', '경찰병원', 155886, 156244, 312130, '3호선', '고속터미널', 790700, 769992, 1560692, '3호선', '교대(법원.검찰청)', 287954, 193269, 481223, '3호선', '구파발', 426486, 395762, 822248, '3호선', '금호', 176454, 166123, 342577, '3호선', '남부터미널(예술의전당)', 597224, 613177, 1210401, '3호선', '녹번', 292274, 260001, 552275, '3호선', '대청', 195313, 178722, 374035, '3호선', '대치', 204268, 198377, 402645, '3호선', '도곡', 101615, 102553, 204168, '3호선', '독립문', 145562, 150621, 296183, '3호선', '동대입구', 160986, 175022, 336008, '3호선', '매봉', 236267, 226859, 463126, '3호선', '무악재', 82399, 83494, 165893, '3호선', '불광', 359488, 392026, 751514, '3호선', '수서', 314169, 319485, 633654, '3호선', '신사', 652082, 694839, 1346921, '3호선', '안국', 367979, 388776, 756755, '3호선', '압구정', 647955, 696112, 1344067, '3호선', '약수', 282668, 274895, 557563, '3호선', '양재(서초구청)', 784122, 845459, 1629581, '3호선', '연신내', 866276, 819105, 1685381, '3호선', '오금', 134947, 118076, 253023, '3호선', '옥수', 189386, 194792, 384178, '3호선', '을지로3가', 218130, 232374, 450504, '3호선', '일원', 174055, 172306, 346361, '3호선', '잠원', 113858, 111698, 225556, '3호선', '종로3가', 220511, 257187, 477698, '3호선', '지축', 66745, 67610, 134355, '3호선', '충무로', 16, 0, 16, '3호선', '학여울', 33910, 33978, 67888, '3호선', '홍제', 377618, 359247, 736865, '4호선', '길음', 433409, 413016, 846425, '4호선', '남태령', 21404, 17964, 39368, '4호선', '노원', 436001, 493327, 929328, '4호선', '당고개', 283458, 263761, 547219, '4호선', '동대문', 436952, 452574, 889526, '4호선', '동대문역사문화공원', 106380, 101833, 208213, '4호선', '동대문역사문화공원(DDP)', 231128, 218120, 449248, '4호선', '동작(현충원)', 53800, 55990, 109790, '4호선', '명동', 368133, 384885, 753018, '4호선', '미아(서울사이버대학)', 347458, 331866, 679324, '4호선', '미아사거리', 640296, 621182, 1261478, '4호선', '사당', 539868, 463962, 1003830, '4호선', '삼각지', 100082, 109652, 209734, '4호선', '상계', 436549, 400887, 837436, '4호선', '서울역', 233849, 299269, 533118, '4호선', '성신여대입구(돈암)', 443058, 422864, 865922, '4호선', '수유(강북구청)', 808980, 802661, 1611641, '4호선', '숙대입구(갈월)', 281306, 277351, 558657, '4호선', '신용산', 319980, 334430, 654410, '4호선', '쌍문', 695068, 629920, 1324988, '4호선', '이촌(국립중앙박물관)', 130509, 152728, 283237, '4호선', '창동', 588451, 627951, 1216402, '4호선', '총신대입구(이수)', 414091, 455728, 869819, '4호선', '충무로', 576883, 599179, 1176062, '4호선', '한성대입구(삼선교)', 288785, 281548, 570333, '4호선', '혜화', 621527, 635234, 1256761, '4호선', '회현(남대문시장)', 480125, 513436, 993561, '5호선', '강동', 431790, 382654, 814444, '5호선', '개롱', 130831, 136524, 267355, '5호선', '개화산', 124177, 120462, 244639, '5호선', '거여', 160593, 151547, 312140, '5호선', '고덕', 171444, 174825, 346269, '5호선', '공덕', 289190, 311447, 600637, '5호선', '광나루(장신대)', 279728, 255150, 534878, '5호선', '광화문(세종문화회관)', 617395, 644406, 1261801, '5호선', '군자(능동)', 247354, 268166, 515520, '5호선', '굽은다리(강동구민회관앞)', 192422, 180890, 373312, '5호선', '길동', 158998, 167956, 326954, '5호선', '김포공항', 128715, 120548, 249263, '5호선', '까치산', 665693, 634525, 1300218, '5호선', '답십리', 352941, 322350, 675291, '5호선', '동대문역사문화공원', 18529, 20987, 39516, '5호선', '동대문역사문화공원(DDP)', 39477, 45226, 84703, '5호선', '둔촌동', 174091, 174518, 348609, '5호선', '마곡', 169318, 160993, 330311, '5호선', '마장', 120186, 114307, 234493, '5호선', '마천', 115195, 116521, 231716, '5호선', '마포', 294900, 304527, 599427, '5호선', '명일', 161888, 167009, 328897, '5호선', '목동', 367658, 405392, 773050, '5호선', '발산', 388601, 402550, 791151, '5호선', '방이', 145436, 149503, 294939, '5호선', '방화', 145949, 137995, 283944, '5호선', '상일동', 365370, 315979, 681349, '5호선', '서대문', 365483, 375147, 740630, '5호선', '송정', 155504, 144873, 300377, '5호선', '신금호', 129773, 133208, 262981, '5호선', '신길', 81541, 90099, 171640, '5호선', '신정(은행정)', 300896, 232676, 533572, '5호선', '아차산(어린이대공원후문)', 319339, 314865, 634204, '5호선', '애오개', 148247, 148656, 296903, '5호선', '양평', 158983, 158863, 317846, '5호선', '여의나루', 242205, 254995, 497200, '5호선', '여의도', 535631, 561148, 1096779, '5호선', '영등포구청', 85071, 85430, 170501, '5호선', '영등포시장', 196196, 201684, 397880, '5호선', '오금', 76338, 76976, 153314, '5호선', '오목교(목동운동장앞)', 481845, 515928, 997773, '5호선', '올림픽공원(한국체대)', 78270, 68500, 146770, '5호선', '왕십리(성동구청)', 97485, 109507, 206992, '5호선', '우장산', 286842, 285342, 572184, '5호선', '을지로4가', 125135, 128732, 253867, '5호선', '장한평', 391607, 389803, 781410, '5호선', '종로3가', 244882, 246378, 491260, '5호선', '천호(풍납토성)', 394354, 410970, 805324, '5호선', '청구', 89659, 80111, 169770, '5호선', '충정로(경기대입구)', 91818, 93642, 185460, '5호선', '행당', 171487, 152631, 324118, '5호선', '화곡', 644708, 595791, 1240499, '6호선', '고려대(종암)', 163265, 157231, 320496, '6호선', '공덕', 387825, 378092, 765917, '6호선', '광흥창(서강)', 184251, 178380, 362631, '6호선', '구산', 163663, 118338, 282001, '6호선', '녹사평(용산구청)', 116876, 120071, 236947, '6호선', '대흥(서강대앞)', 165455, 172399, 337854, '6호선', '독바위', 61997, 68412, 130409, '6호선', '돌곶이', 204412, 192492, 396904, '6호선', '동묘앞', 180859, 182260, 363119, '6호선', '디지털미디어시티', 289969, 311205, 601174, '6호선', '마포구청', 303390, 269823, 573213, '6호선', '망원', 314318, 344498, 658816, '6호선', '버티고개', 48035, 46439, 94474, '6호선', '보문', 164067, 151501, 315568, '6호선', '봉화산(서울의료원)', 202073, 183271, 385344, '6호선', '불광', 101115, 102149, 203264, '6호선', '삼각지', 123370, 105258, 228628, '6호선', '상수', 186941, 216224, 403165, '6호선', '상월곡(한국과학기술연구원)', 133339, 117826, 251165, '6호선', '새절(신사)', 281953, 263805, 545758, '6호선', '석계', 277829, 282604, 560433, '6호선', '신내', 1, 0, 1, '6호선', '신당', 177188, 188497, 365685, '6호선', '안암(고대병원앞)', 211183, 212140, 423323, '6호선', '약수', 79227, 79904, 159131, '6호선', '역촌', 80886, 95785, 176671, '6호선', '연신내', 11, 0, 11, '6호선', '월곡(동덕여대)', 250558, 244760, 495318, '6호선', '월드컵경기장(성산)', 105181, 108484, 213665, '6호선', '응암', 387682, 384981, 772663, '6호선', '이태원', 271770, 295559, 567329, '6호선', '증산(명지대앞)', 228842, 222859, 451701, '6호선', '창신', 75009, 60205, 135214, '6호선', '청구', 84349, 92785, 177134, '6호선', '태릉입구', 119120, 132228, 251348, '6호선', '한강진', 156162, 186869, 343031, '6호선', '합정', 302329, 293499, 595828, '6호선', '화랑대(서울여대입구)', 241503, 185541, 427044, '6호선', '효창공원앞', 151232, 135459, 286691, '7호선', '가산디지털단지', 930227, 938305, 1868532, '7호선', '강남구청', 342222, 383566, 725788, '7호선', '건대입구', 271945, 286188, 558133, '7호선', '고속터미널', 311354, 266508, 577862, '7호선', '공릉(서울과학기술대)', 256503, 259452, 515955, '7호선', '광명사거리', 526281, 517870, 1044151, '7호선', '군자(능동)', 327335, 257433, 584768, '7호선', '굴포천', 193473, 204381, 397854, '7호선', '까치울', 163133, 155115, 318248, '7호선', '남구로', 345416, 363498, 708914, '7호선', '남성', 244048, 227610, 471658, '7호선', '내방', 300395, 307630, 608025, '7호선', '노원', 421736, 448131, 869867, '7호선', '논현', 446209, 487397, 933606, '7호선', '대림(구로구청)', 152657, 150323, 302980, '7호선', '도봉산', 206695, 251182, 457877, '7호선', '뚝섬유원지', 216486, 219773, 436259, '7호선', '마들', 258643, 245964, 504607, '7호선', '먹골', 232700, 225787, 458487, '7호선', '면목', 353834, 343423, 697257, '7호선', '반포', 124332, 123070, 247402, '7호선', '보라매', 202001, 200311, 402312, '7호선', '부천시청', 263285, 261308, 524593, '7호선', '부천종합운동장', 103668, 90570, 194238, '7호선', '부평구청', 255731, 208893, 464624, '7호선', '사가정', 359281, 360283, 719564, '7호선', '삼산체육관', 99260, 87835, 187095, '7호선', '상도', 222136, 213484, 435620, '7호선', '상동', 274440, 282213, 556653, '7호선', '상봉(시외버스터미널)', 390764, 368037, 758801, '7호선', '수락산', 290195, 291676, 581871, '7호선', '숭실대입구(살피재)', 246799, 248155, 494954, '7호선', '신대방삼거리', 362754, 346108, 708862, '7호선', '신중동', 310111, 309776, 619887, '7호선', '신풍', 236542, 225400, 461942, '7호선', '어린이대공원(세종대)', 249362, 245048, 494410, '7호선', '온수(성공회대입구)', 225251, 210720, 435971, '7호선', '용마산', 42199, 40341, 82540, '7호선', '용마산(용마폭포공원)', 95240, 91474, 186714, '7호선', '이수', 345045, 338298, 683343, '7호선', '장승배기', 220480, 213660, 434140, '7호선', '장암', 55732, 22677, 78409, '7호선', '중계', 302472, 268988, 571460, '7호선', '중곡', 217933, 203222, 421155, '7호선', '중화', 252454, 243862, 496316, '7호선', '천왕', 212132, 195964, 408096, '7호선', '철산', 469885, 481459, 951344, '7호선', '청담', 421636, 467862, 889498, '7호선', '춘의', 208789, 205117, 413906, '7호선', '태릉입구', 177125, 161793, 338918, '7호선', '하계', 375981, 353675, 729656, '7호선', '학동', 508647, 548391, 1057038, '8호선', '가락시장', 170292, 193437, 363729, '8호선', '강동구청', 219694, 226256, 445950, '8호선', '남한산성입구(성남법원.검찰청)', 287235, 258328, 545563, '8호선', '단대오거리', 225529, 217105, 442634, '8호선', '모란', 93994, 71141, 165135, '8호선', '몽촌토성(평화의문)', 115120, 121499, 236619, '8호선', '문정', 441432, 462742, 904174, '8호선', '복정', 216061, 184853, 400914, '8호선', '산성', 118317, 117509, 235826, '8호선', '석촌', 165151, 193269, 358420, '8호선', '송파', 181596, 173639, 355235, '8호선', '수진', 107933, 97673, 205606, '8호선', '신흥', 100489, 106716, 207205, '8호선', '암사', 404583, 357664, 762247, '8호선', '잠실(송파구청)', 299449, 338005, 637454, '8호선', '장지', 362396, 352653, 715049, '8호선', '천호(풍납토성)', 371853, 425354, 797207, '9호선', '가양', 436022, 422991, 859013, '9호선', '개화', 54163, 38696, 92859, '9호선', '고속터미널', 216538, 281079, 497617, '9호선', '공항시장', 64285, 71751, 136036, '9호선', '구반포', 51867, 54587, 106454, '9호선', '국회의사당', 310800, 311348, 622148, '9호선', '김포공항', 140006, 171777, 311783, '9호선', '노들', 90922, 78294, 169216, '9호선', '노량진', 572680, 577859, 1150539, '9호선', '당산', 381631, 372852, 754483, '9호선', '동작(현충원)', 42580, 33966, 76546, '9호선', '등촌', 218274, 218560, 436834, '9호선', '마곡나루', 68062, 68545, 136607, '9호선', '마곡나루(서울식물원)', 150789, 150877, 301666, '9호선', '사평', 52936, 52432, 105368, '9호선', '샛강', 107074, 111439, 218513, '9호선', '선유도', 148526, 144263, 292789, '9호선', '신논현', 665270, 675648, 1340918, '9호선', '신목동', 76333, 69286, 145619, '9호선', '신반포', 50876, 52289, 103165, '9호선', '신방화', 142275, 138469, 280744, '9호선', '양천향교', 189008, 195715, 384723, '9호선', '여의도', 460898, 447553, 908451, '9호선', '염창', 361002, 354505, 715507, '9호선', '증미', 148126, 148923, 297049, '9호선', '흑석(중앙대입구)', 154805, 163889, 318694, '9호선2~3단계', '둔촌오륜', 16855, 16036, 32891, '9호선2~3단계', '봉은사', 296468, 296998, 593466, '9호선2~3단계', '삼성중앙', 127804, 132643, 260447, '9호선2~3단계', '삼전', 136125, 132702, 268827, '9호선2~3단계', '석촌', 155282, 134250, 289532, '9호선2~3단계', '석촌고분', 116536, 115881, 232417, '9호선2~3단계', '선정릉', 186660, 200532, 387192, '9호선2~3단계', '송파나루', 91887, 97208, 189095, '9호선2~3단계', '언주', 197138, 198463, 395601, '9호선2~3단계', '올림픽공원(한국체대)', 102838, 101626, 204464, '9호선2~3단계', '종합운동장', 86366, 82816, 169182, '9호선2~3단계', '중앙보훈병원', 185048, 167901, 352949, '9호선2~3단계', '한성백제', 47753, 41501, 89254]

실행결과:
 [['1호선', '동대문', 253079, 250266, 503345],
 ['1호선', '동묘앞', 201255, 210176, 411431],
 ['1호선', '서울역', 815894, 776303, 1592197],
 ['1호선', '시청', 437824, 444220, 882044],
 ['1호선', '신설동', 314759, 307700, 622459],
 ['1호선', '제기동', 362048, 370559, 732607],
 ['1호선', '종각', 744396, 728555, 1472951],
 ['1호선', '종로3가', 555451, 525826, 1081277],
 ['1호선', '종로5가', 468370, 472936, 941306],
 ['1호선', '청량리(서울시립대입구)', 454237, 450838, 905075],
 ['2호선', '강남', 1880213, 1903343, 3783556],
 ['2호선', '강변(동서울터미널)', 706391, 696987, 1403378],
 ....
 ....
 ['9호선2~3단계', '올림픽공원(한국체대)', 102838, 101626, 204464],
 ['9호선2~3단계', '종합운동장', 86366, 82816, 169182],
 ['9호선2~3단계', '중앙보훈병원', 185048, 167901, 352949],
 ['9호선2~3단계', '한성백제', 47753, 41501, 89254]]

__(2) data list를 사용하여 역명으로 구별되고, 각 항목이 사전 형식인 station_dict를 생성하세요.<br> (key:  "호선", "역명", "승차총승객수", "하차총승객수", "총유동인구수")__<br>

실행결과:
[{'호선': '1호선',
  '역명': '동대문',
  '승차총승객수': 253079,
  '하차총승객수': 250266,
  '총유동인구수': 503345},
 {'호선': '1호선',
  '역명': '동묘앞',
  '승차총승객수': 201255,
  '하차총승객수': 210176,
  '총유동인구수': 411431},
 {'호선': '1호선',
  '역명': '서울역',
  '승차총승객수': 815894,
  '하차총승객수': 776303,
  '총유동인구수': 1592197},...

__(3) station_list에서 1호선 역 이름만 추출하세요.__

__(4) 2000년 3월 서울 지하철역 이용 현황 정보 중 총유동인구수가 가장 많은 역과 해당 역의 총유동인구수를 출력하세요.__

실행결과:
유동인구가 가장 많은 역:  강남
총유동인구수:  3783556

__(5) 2000년 3월 서울의 모든 지하철역의 총유동인구의 합을 구하세요.__

##  < 리스트의 슬라이싱과 인덱싱에 관한 tips>

+ __리스트의 슬라이싱과 인덱싱에 관한 다음의 사항을 확인해 보세요.__

__[3] num_list = [0, 1,2,3,4,5,6,7,8,9]인 리스트 l을 생성하세요.__

In [ ]:
num_list = list(range(10))
num_list

__(1) 리스트 항목을 변경할 때 할당할 항목의 갯수가 맞지 않는 경우, 리스트 항목이 어떻게 변하는지 확인하세요.__

In [ ]:
num_list[2:5] = [20, 30] #할당할 항목의 갯수가 맞지 않는 경우 리스트의 항목 수 변경됨
num_list

__(2) del()함수를 사용하여 list slicing 객체를 삭제할 수 있음을 확인하세요.__

In [ ]:
del(num_list[5:7]) 
num_list

__(3) list 항목을 할당할 때 slicing 과 step을 이용해서 할당할 수 있음을 확인하세요.__

In [ ]:
num_list[3::2] = [11, 22]
num_list

__(4) 다음의 두 가지 코드를 실행시켜 보세요. 할당문의 대상이 슬라이스인 경우, 항목 하나만 할당하는 경우에도 할당문 오른쪽에는 반드시 반복 가능한 객체가 와야 함을 확인하세요__

In [ ]:
num_list[2:5] = 100

In [ ]:
num_list[2:5] = [100]
num_list

#  <사전(Dictionary) 생성>

__[4] 다음은 김철수씨의 이번 주 점심 식사 지출 내역입니다.__

|요일 |   메뉴     | 가격|
|---- |------------|-----|
|'Mon'|'sandwich' | 6.0 |
|'Tue'|'hamburger' | 5.0 |
|'Wed'|'taco'|7.0|
|'Thu'|'burrito'|8.0|
|'Fri'|'steak'|20.0|

__(1) 요일-메뉴로 이루어진 lunch 딕셔너리를 만들고 출력하세요__

__(2) lunch 딕셔너리에서 월요일 메뉴를 출력하세요__

__(3) lunch딕셔너리를 사용하여 메뉴-요일로 이루어진 reverse_lunch 딕셔너리를 출력하세요(items() 메서드를 사용하세요)__

__(4) 이차원 딕셔너리 lunch_price를 생성하세요. 최상위 키는 "요일"로 하고, 각 요일은 메뉴와 가격을 키와 값으로 합니다.</br>
lunch_price 딕셔너리에서 burrito가격을 출력하세요.__

__(5) lunch_price의 메뉴를 리스트로 출력하세요__

__(6) lunch_price 딕셔너리에서 점심 식사로 지출한 비용이 8.0보다 작은 요일만 출력하되, 요일을 첫 글자를 대문자로 변화하여 출력하세요.__

# <복잡한 사전(Dictionary) 값 참조하기>

__[6] 2020년 3월 서울 지하철역 유동인구 정보를 분석하고 지도에 표시하려고 합니다.<br> 
google map platform(https://developers.google.com/maps/documentation/geocoding/overview)에서 제공하는 api를 사용하여 "동대문역"의 지리 정보를 얻어 json 변수에 할당하였습니다.__

json = {'results': [{'address_components': [{'long_name': '２８８', 'short_name': '２８８', 'types': ['premise']}, {'long_name': '종로', 'short_name': '종로', 'types': ['political', 'sublocality', 'sublocality_level_4']}, {'long_name': '종로6가', 'short_name': '종로6가', 'types': ['political', 'sublocality', 'sublocality_level_2']}, {'long_name': '종로구', 'short_name': '종로구', 'types': ['political', 'sublocality', 'sublocality_level_1']}, {'long_name': '서울특별시', 'short_name': '서울특별시', 'types': ['administrative_area_level_1', 'political']}, {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']}, {'long_name': '110-126', 'short_name': '110-126', 'types': ['postal_code']}], 'formatted_address': '대한민국 서울특별시 종로구 종로6가 종로 288', 'geometry': {'location': {'lat': 37.5711389, 'lng': 127.0095452}, 'location_type': 'ROOFTOP', 'viewport': {'northeast': {'lat': 37.5724878802915, 'lng': 127.0108941802915}, 'southwest': {'lat': 37.5697899197085, 'lng': 127.0081962197085}}}, 'place_id': 'ChIJm6x0HTujfDURbf9iX8DtJ2A', 'types': ['establishment', 'point_of_interest', 'tourist_attraction']}], 'status': 'OK'}

__(1)동대문역의 주소('대한민국 서울특별시 종로구 종로6가 종로 288')를 추출하여, long_addr 변수에 저장하세요.__

__(2) 동대문역의 위도(37.5711389), 경도(127.0095452) 정보를 추출하여, lat, lng변수에 저장하세요.__

#  <제어문>

__[7] 다음은 A사 제품에 대한 연도별 고객 만족도 점수입니다. 연도별 점수를  연도별 등급으로 출력하세요__

|연도 |   고객 만족도 | 
|---- |------------|
|2015|95 | 
|2016|85 | 
|2017|75|
|2018|65|
|2019|50|
</br>

- 만족도 등급<br>
    1) 90 ~ 100 : 매우 만족<br>
    2) 80 ~ 89  : 만족<br>
    3) 70 ~ 79  : 보통<br>
    4) 60 ~ 69  : 불만<br>
    5) 기타     : 매우 불만<br>

__[8] 초항과 공차를 입력받아 등차수열을 만들고, 등차수열의 1항부터 20번째 항으로 이루어진 리스트를 출력하세요__

__[9] 1 ~ 50 사이의 임의의 숫자를 입력받아 1부터 입력한 수까지 "369게임"을 프로그램하세요__
+ **게임룰<br>**
    1) 숫자에 3, 6, 9가 들어가는 경우: **"박수"**를 출력한다<br>
    2) 10의 배수인 경우: **"뽀숑"**을 출력한다. <br>
    3) 1), 2)가 모두 해당하는 경우, **"박수"**를 출력한다<br>
    4) 나머지 경우 : 숫자를 출력한다.
    
+ **게임 예<br>**
    33을 입력한 경우<br>
    1, 2, 박수, 4, 5, 박수, 7, 8, 박수, 뽀숑, 11, 12, 박수, 14, 15, 박수, 17, 18, 박수, 뽀숑, 21, 22, 박수, 24, 25, 박수, 28, 박수, 박수, 박수, 박수, 박수

__[10] range()함수는 정해진 범위(start, end, step)의 정수를 발생시키는 제너레이터입니다.<br> range() 함수와 유사하게 작동하되, 특정 범위의 부동 소수점 숫자(시작값 0, 끝값 4, 증감분을 0.5)를 만드는 함수 frange()를 작성하고 생성된 값을 출력하세요__

def frange(start, stop, increment):
    코드 작성부분

실행결과: frange(0, 4, 0.5)
[0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5]